BEGIN TRANSACTION;
INSERT INTO principal_departamento VALUES (5, 'ANTIOQUIA');
INSERT INTO principal_departamento VALUES (8, 'ATLANTICO');
INSERT INTO principal_departamento VALUES (11, 'BOGOTÁ');
INSERT INTO principal_departamento VALUES (13, 'BOLIVAR');
INSERT INTO principal_departamento VALUES (15, 'BOYACA');
INSERT INTO principal_departamento VALUES (17, 'CALDAS');
INSERT INTO principal_departamento VALUES (18, 'CAQUETA');
INSERT INTO principal_departamento VALUES (19, 'CAUCA');
INSERT INTO principal_departamento VALUES (20, 'CESAR');
INSERT INTO principal_departamento VALUES (23, 'CÓRDOBA');
INSERT INTO principal_departamento VALUES (25, 'CUNDINAMARCA');
INSERT INTO principal_departamento VALUES (27, 'CHOCO');
INSERT INTO principal_departamento VALUES (41, 'HUILA');
INSERT INTO principal_departamento VALUES (44, 'LA GUAJIRA');
INSERT INTO principal_departamento VALUES (47, 'MAGDALENA');
INSERT INTO principal_departamento VALUES (50, 'META');
INSERT INTO principal_departamento VALUES (52, 'NARIÑO');
INSERT INTO principal_departamento VALUES (54, 'NORTE DE SANTANDER');
INSERT INTO principal_departamento VALUES (63, 'QUINDIO');
INSERT INTO principal_departamento VALUES (66, 'RISARALDA');
INSERT INTO principal_departamento VALUES (68, 'SANTANDER');
INSERT INTO principal_departamento VALUES (70, 'SUCRE');
INSERT INTO principal_departamento VALUES (73, 'TOLIMA');
INSERT INTO principal_departamento VALUES (76, 'VALLE DEL CAUCA');
INSERT INTO principal_departamento VALUES (81, 'ARAUCA');
INSERT INTO principal_departamento VALUES (85, 'CASANARE');
INSERT INTO principal_departamento VALUES (86, 'PUTUMAYO');
INSERT INTO principal_departamento VALUES (88, 'SAN ANDRÉS');
INSERT INTO principal_departamento VALUES (91, 'AMAZONAS');
INSERT INTO principal_departamento VALUES (94, 'GUAINIA');
INSERT INTO principal_departamento VALUES (95, 'GUAVIARE');
INSERT INTO principal_departamento VALUES (97, 'VAUPES');
INSERT INTO principal_departamento VALUES (99, 'VICHADA');
COMMIT;